apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tracerBoxThree.name }}
  labels:
    app: {{ template "hello-docker-chart.name" . }}
    chart: {{ template "hello-docker-chart.chart" . }}
    component: "{{ .Values.tracerBoxThree.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.tracerBoxThree.service.type }}
  ports:
    - port: {{ .Values.tracerBoxThree.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.tracerBoxThree.service.nodePort }}
  selector:
    app: {{ "tracer-box-three" }}
    component: "{{ .Values.tracerBoxThree.name }}"
    release: {{ .Release.Name }}